feat: delist and change price without tests
SigwoTechnologies/leda-web pull request #54
Opened 2022-11-08 14:05 UTC by AlefrankM

2022-11-08 17:44 UTC, GimerStackIt commented on src/features/marketplace/process/clients/delist-item-client.ts
> +    console.log(state);
Remove Console.log

2022-11-08 17:56 UTC, juliswer approved these changes
Looks good.
Just a comment: please try to make shorter PRs, otherwise will be getting hard finding a possible vulnerability, bug or whatever to be fixed before merging main.
If you have many changes, try sending daily PRs, so is easier check you progress.

2022-11-08 17:57 UTC, GimerStackIt approved these changes

2022-11-08 18:55 UTC, mmiranda-stackit requested changes
See my comments. I didn't see any unit test here.

2022-11-08 18:55 UTC, mmiranda-stackit commented on src/components/item-details/bid-tab/delisting-tab-content.tsx
> +    dispatch(
Maybe it is good idea to include the withProtection action in here, so we double check that the action should be performed by an authenticated user.

2022-11-08 18:55 UTC, mmiranda-stackit commented on src/features/marketplace/process/commands/change-price-item/store-change-price-item-command.ts
> +    if (!state.marketplaceEvent) return { ...state, error: MarketplaceError.RequiredListEvent };
Why do you need the marketplaceEvent here? And if you happen to need it, you are returning the wrong error.

2022-11-08 18:55 UTC, mmiranda-stackit commented on src/features/marketplace/process/commands/change-price-item/store-change-price-item-command.ts
> +      return { ...state, error: MarketplaceError.StoreListItemFailure };
You should throw the proper error here, StoreChangePriceFailure or something like that

2022-11-08 18:55 UTC, mmiranda-stackit commented on src/features/marketplace/process/commands/delist-item/change-status-item-command.ts
> +    if (!state.ownerAddress) return { ...state, error: MarketplaceError.RequiredOwnerAddress };
This ownerAddress check is not needed

2022-11-08 18:55 UTC, mmiranda-stackit commented on src/features/marketplace/process/commands/delist-item/store-delist-item-command.ts
> +    if (!state.marketplaceEvent) return { ...state, error: MarketplaceError.RequiredListEvent };
You are missing the ownerAddress check. The marketplaceEvent is not required here

2022-11-08 18:55 UTC, mmiranda-stackit commented on src/features/marketplace/process/commands/delist-item/store-delist-item-command.ts
> +      return { ...state, error: MarketplaceError.StoreListItemFailure };
The error is wrong. You should return the StoreDelistItemFailure instead

2022-11-08 18:55 UTC, mmiranda-stackit commented on src/features/marketplace/process/invokers/list-item-invoker.ts
> +    if (!this.state.error) this.state = await this.onStoreDelistItemCommand.execute(this.state);
How come you are changing list by delist in the list item invoker?

2022-11-08 18:55 UTC, mmiranda-stackit commented on src/features/marketplace/store/marketplace.actions.ts
> +        openToastSuccess('The item has been successfully changed price on the marketplace.')
Change the label to something like 'The item price has been successfully changed"

2022-11-08 21:15 UTC, AlefrankM commented on src/components/item-details/bid-tab/delisting-tab-content.tsx
> +                className={isLoading ? 'disabled' : ''}
Yeas, you can't click it

2022-11-08 23:53 UTC, mmiranda-stackit commented on src/features/marketplace/process/commands/change-price-item/change-price-item-command.ts
> +        error: MarketplaceError.ChangeStatusItemFailure,
ChangeItemPriceFailure?

2022-11-09 01:23 UTC, mmiranda-stackit approved these changes
nicely done

2022-11-09 01:25 UTC, merged